### ISSUE TITLE
Failed to generate mimic-cxr-2.0.0-jpeg-txt.csv

### ISSUE THREAD

**Issue by Zoew420** [Wang-Yuanlong/MultimodalPred#2]
Sorry, I'm sorry to bother you. 
I followed the instruction of build mimic-cxr-2.0.0-jpeg-txt.csv mentioned in [#issue-1800109179](https://github.com/Wang-Yuanlong/MultimodalPred/issues/1#issue-1800109179),
but I found that the generated mimic-cxr-2.0.0-jpeg-txt.csv is **empty** since there is **no '.txt' file** in [MIMIC-CXR-JPG](https://physionet.org/content/mimic-cxr-jpg/2.0.0/) database.
Could you please provide the **folder format and sample** of the MIMIC-CXR-JPG database you use? If it is convenient, could you provide the download address?
Thanks a lot!

**Comment by Wang-Yuanlong** [comment]
Hi,

I'm not sure what the ".txt" file refers to, but I think you can find it from the original [MIMIC-CXR](https://physionet.org/content/mimic-cxr/2.0.0/) dataset.

**Comment by Zoew420** [comment]
Thank you very much for your reply.

According to the `build_mimic_cxr_jpg_dataframe` function description on line 1722 in MIMIC_IV_HAIM_API.py:
```
if extension=='.txt':
  note = open(subdir + '/' + filename + extension, "r", errors='ignore')
  img_note_text = note.read()
  note.close()
  img_folder = subdir + '/' + filename
  
  for img_subdir, img_dirs, img_files in os.walk(img_folder):
      for img_file in img_files:
          # Extract filename and extension to filter by CSV only
          img_filename, img_extension = os.path.splitext(img_file)
          if img_extension=='.jpg':
              df_mimic_cxr_jpg = df_mimic_cxr_jpg.append({'Note_folder': subdir.replace(core_mimiciv_imgcxr_path,''), 'Note_file': filename + extension , 'Note': img_note_text, 'Img_Folder': img_folder.replace(core_mimiciv_imgcxr_path,''), 'Img_Filename': img_filename + img_extension, 'dicom_id': img_filename}, ignore_index=True)
```
                            
It finds the '.txt' file and reads the notes message, then reads the '.jpg' message in the same directory and adds it to the mimic-cxr-2.0.0-jpeg-txt.csv file. However, [MIMIC-CXR-JPG](https://physionet.org/content/mimic-cxr-jpg/2.0.0/) database without any '. txt' file. 

If we want to generate mimic-cxr-2.0.0-jpeg-txt.csv, should we need to download the origin [MIMIC-CXR](https://physionet.org/content/mimic-cxr/2.0.0/) database and change the code from the `if img_extension == 'jpg' ` to `if img_extension=='.dcm'`.

Thank you for your help!

**Comment by TYTYTY19** [comment]
> Thank you very much for your reply.非常感谢您的回复。
> 
> According to the `build_mimic_cxr_jpg_dataframe` function description on line 1722 in MIMIC_IV_HAIM_API.py:根据 MIMIC_IV_HAIM_API.py 中第 1722 行的 `build_mimic_cxr_jpg_dataframe` 函数描述：
> 
> ```
> if extension=='.txt':
>   note = open(subdir + '/' + filename + extension, "r", errors='ignore')
>   img_note_text = note.read()
>   note.close()
>   img_folder = subdir + '/' + filename
>   
>   for img_subdir, img_dirs, img_files in os.walk(img_folder):
>       for img_file in img_files:
>           # Extract filename and extension to filter by CSV only
>           img_filename, img_extension = os.path.splitext(img_file)
>           if img_extension=='.jpg':
>               df_mimic_cxr_jpg = df_mimic_cxr_jpg.append({'Note_folder': subdir.replace(core_mimiciv_imgcxr_path,''), 'Note_file': filename + extension , 'Note': img_note_text, 'Img_Folder': img_folder.replace(core_mimiciv_imgcxr_path,''), 'Img_Filename': img_filename + img_extension, 'dicom_id': img_filename}, ignore_index=True)
> ```
> 
> It finds the '.txt' file and reads the notes message, then reads the '.jpg' message in the same directory and adds it to the mimic-cxr-2.0.0-jpeg-txt.csv file. However, [MIMIC-CXR-JPG](https://physionet.org/content/mimic-cxr-jpg/2.0.0/) database without any '. txt' file.它找到 '.txt' 文件并读取 notes 消息，然后读取同一目录中的 '.jpg' 消息并将其添加到 mimic-cxr-2.0.0-jpeg-txt.csv 文件中。但是，MIMIC-CXR-JPG 数据库没有任何 '.txt“文件。
> 
> If we want to generate mimic-cxr-2.0.0-jpeg-txt.csv, should we need to download the origin [MIMIC-CXR](https://physionet.org/content/mimic-cxr/2.0.0/) database and change the code from the `if img_extension == 'jpg' ` to `if img_extension=='.dcm'`.如果我们要生成 mimic-cxr-2.0.0-jpeg-txt.csv，我们是否需要下载原始 MIMIC-CXR 数据库并将代码从 `if img_extension == 'jpg' ` 更改为 `if img_extension=='.dcm'` 。
> 
> Thank you for your help! 感谢您的帮助！

Sorry to bother you, I also meet this question, can you give me some advice?

**Comment by Zoew420** [comment]
> the original [MIMIC-CXR](https://physionet.org/content/mimic-cxr/2.0.0/) dataset

Download the original [MIMIC-CXR](https://physionet.org/content/mimic-cxr/2.0.0/) dataset

**Comment by Zoew420** [comment]
> > Thank you very much for your reply.非常感谢您的回复。
> > According to the `build_mimic_cxr_jpg_dataframe` function description on line 1722 in MIMIC_IV_HAIM_API.py:根据 MIMIC_IV_HAIM_API.py 中第 1722 行的 `build_mimic_cxr_jpg_dataframe` 函数描述：
> > ```
> > if extension=='.txt':
> >   note = open(subdir + '/' + filename + extension, "r", errors='ignore')
> >   img_note_text = note.read()
> >   note.close()
> >   img_folder = subdir + '/' + filename
> >   
> >   for img_subdir, img_dirs, img_files in os.walk(img_folder):
> >       for img_file in img_files:
> >           # Extract filename and extension to filter by CSV only
> >           img_filename, img_extension = os.path.splitext(img_file)
> >           if img_extension=='.jpg':
> >               df_mimic_cxr_jpg = df_mimic_cxr_jpg.append({'Note_folder': subdir.replace(core_mimiciv_imgcxr_path,''), 'Note_file': filename + extension , 'Note': img_note_text, 'Img_Folder': img_folder.replace(core_mimiciv_imgcxr_path,''), 'Img_Filename': img_filename + img_extension, 'dicom_id': img_filename}, ignore_index=True)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It finds the '.txt' file and reads the notes message, then reads the '.jpg' message in the same directory and adds it to the mimic-cxr-2.0.0-jpeg-txt.csv file. However, [MIMIC-CXR-JPG](https://physionet.org/content/mimic-cxr-jpg/2.0.0/) database without any '. txt' file.它找到 '.txt' 文件并读取 notes 消息，然后读取同一目录中的 '.jpg' 消息并将其添加到 mimic-cxr-2.0.0-jpeg-txt.csv 文件中。但是，MIMIC-CXR-JPG 数据库没有任何 '.txt“文件。
> > If we want to generate mimic-cxr-2.0.0-jpeg-txt.csv, should we need to download the origin [MIMIC-CXR](https://physionet.org/content/mimic-cxr/2.0.0/) database and change the code from the `if img_extension == 'jpg' ` to `if img_extension=='.dcm'`.如果我们要生成 mimic-cxr-2.0.0-jpeg-txt.csv，我们是否需要下载原始 MIMIC-CXR 数据库并将代码从 `if img_extension == 'jpg' ` 更改为 `if img_extension=='.dcm'` 。
> > Thank you for your help! 感谢您的帮助！
> 
> Sorry to bother you, I also meet this question, can you give me some advice?

Download  the original [MIMIC-CXR](https://physionet.org/content/mimic-cxr/2.0.0/) dataset.

**Comment by TYTYTY19** [comment]
> > > Thank you very much for your reply.非常感谢您的回复。
> > > According to the `build_mimic_cxr_jpg_dataframe` function description on line 1722 in MIMIC_IV_HAIM_API.py:根据 MIMIC_IV_HAIM_API.py 中第 1722 行的 `build_mimic_cxr_jpg_dataframe` 函数描述：
> > > ```
> > > if extension=='.txt':
> > >   note = open(subdir + '/' + filename + extension, "r", errors='ignore')
> > >   img_note_text = note.read()
> > >   note.close()
> > >   img_folder = subdir + '/' + filename
> > >   
> > >   for img_subdir, img_dirs, img_files in os.walk(img_folder):
> > >       for img_file in img_files:
> > >           # Extract filename and extension to filter by CSV only
> > >           img_filename, img_extension = os.path.splitext(img_file)
> > >           if img_extension=='.jpg':
> > >               df_mimic_cxr_jpg = df_mimic_cxr_jpg.append({'Note_folder': subdir.replace(core_mimiciv_imgcxr_path,''), 'Note_file': filename + extension , 'Note': img_note_text, 'Img_Folder': img_folder.replace(core_mimiciv_imgcxr_path,''), 'Img_Filename': img_filename + img_extension, 'dicom_id': img_filename}, ignore_index=True)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It finds the '.txt' file and reads the notes message, then reads the '.jpg' message in the same directory and adds it to the mimic-cxr-2.0.0-jpeg-txt.csv file. However, [MIMIC-CXR-JPG](https://physionet.org/content/mimic-cxr-jpg/2.0.0/) database without any '. txt' file.它找到 '.txt' 文件并读取 notes 消息，然后读取同一目录中的 '.jpg' 消息并将其添加到 mimic-cxr-2.0.0-jpeg-txt.csv 文件中。但是，MIMIC-CXR-JPG 数据库没有任何 '.txt“文件。
> > > If we want to generate mimic-cxr-2.0.0-jpeg-txt.csv, should we need to download the origin [MIMIC-CXR](https://physionet.org/content/mimic-cxr/2.0.0/) database and change the code from the `if img_extension == 'jpg' ` to `if img_extension=='.dcm'`.如果我们要生成 mimic-cxr-2.0.0-jpeg-txt.csv，我们是否需要下载原始 MIMIC-CXR 数据库并将代码从 `if img_extension == 'jpg' ` 更改为 `if img_extension=='.dcm'` 。
> > > Thank you for your help! 感谢您的帮助！
> > 
> > 
> > Sorry to bother you, I also meet this question, can you give me some advice?
> 
> Download the original [MIMIC-CXR](https://physionet.org/content/mimic-cxr/2.0.0/) dataset.下载原始 MIMIC-CXR 数据集。

Thanks for your timely reply, I am downloading the ' mimic-cxr-reports.zip ' file in the original mimic-cxr dataset. According to the description of the build _ mimic _ cxr _ jpg _ dataframe function, do I not need to change the code from if img _ extension = = ' jpg ' to if img _ extension = = '.dcm ' ?

**Comment by TYTYTY19** [comment]
> > > Thank you very much for your reply.非常感谢您的回复。
> > > According to the `build_mimic_cxr_jpg_dataframe` function description on line 1722 in MIMIC_IV_HAIM_API.py:根据 MIMIC_IV_HAIM_API.py 中第 1722 行的 `build_mimic_cxr_jpg_dataframe` 函数描述：根据 MIMIC_IV_HAIM_API.py 中第 1722 行的 `build_mimic_cxr_jpg_dataframe` 函数描述：根据 MIMIC_IV_HAIM_API.py 中第 1722 行的 `build_mimic_cxr_jpg_dataframe` 函数描述：
> > > ```
> > > if extension=='.txt':
> > >   note = open(subdir + '/' + filename + extension, "r", errors='ignore')
> > >   img_note_text = note.read()
> > >   note.close()
> > >   img_folder = subdir + '/' + filename
> > >   
> > >   for img_subdir, img_dirs, img_files in os.walk(img_folder):
> > >       for img_file in img_files:
> > >           # Extract filename and extension to filter by CSV only
> > >           img_filename, img_extension = os.path.splitext(img_file)
> > >           if img_extension=='.jpg':
> > >               df_mimic_cxr_jpg = df_mimic_cxr_jpg.append({'Note_folder': subdir.replace(core_mimiciv_imgcxr_path,''), 'Note_file': filename + extension , 'Note': img_note_text, 'Img_Folder': img_folder.replace(core_mimiciv_imgcxr_path,''), 'Img_Filename': img_filename + img_extension, 'dicom_id': img_filename}, ignore_index=True)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It finds the '.txt' file and reads the notes message, then reads the '.jpg' message in the same directory and adds it to the mimic-cxr-2.0.0-jpeg-txt.csv file. However, [MIMIC-CXR-JPG](https://physionet.org/content/mimic-cxr-jpg/2.0.0/) database without any '. txt' file.它找到 '.txt' 文件并读取 notes 消息，然后读取同一目录中的 '.jpg' 消息并将其添加到 mimic-cxr-2.0.0-jpeg-txt.csv 文件中。但是，MIMIC-CXR-JPG 数据库没有任何 '.txt“文件。它找到 '.txt' 文件并读取 notes 消息，然后读取同一目录中的 '.jpg' 消息并将其添加到 mimic-cxr-2.0.0-jpeg-txt.csv 文件中。但是，MIMIC-CXR-JPG 数据库没有任何 '.txt' file.它找到 '.txt' 文件并读取 notes 消息，然后读取同一目录中的 '.jpg' 消息并将其添加到 mimic-cxr-2.0.0-jpeg-txt.csv 文件中。但是，MIMIC-CXR-JPG 数据库没有任何 '.txt“文件。
> > > If we want to generate mimic-cxr-2.0.0-jpeg-txt.csv, should we need to download the origin [MIMIC-CXR](https://physionet.org/content/mimic-cxr/2.0.0/) database and change the code from the `if img_extension == 'jpg' ` to `if img_extension=='.dcm'`.如果我们要生成 mimic-cxr-2.0.0-jpeg-txt.csv，我们是否需要下载原始 MIMIC-CXR 数据库并将代码从 `if img_extension == 'jpg' ` 更改为 `if img_extension=='.dcm'` 。如果我们想要生成 mimic-cxr-2.0.0-jpeg-txt.csv，我们是否需要下载原始 MIMIC-CXR 数据库并将代码从 `if img_extension == 'jpg' ` 更改为 `if img_extension=='.dcm'` .如果我们要生成 mimic-cxr-2.0.0-jpeg-txt.csv，我们是否需要下载原始 MIMIC-CXR 数据库并将代码从 `if img_extension == 'jpg' ` 更改为 `if img_extension=='.dcm'` 。
> > > Thank you for your help! 感谢您的帮助！
> > 
> > 
> > Sorry to bother you, I also meet this question, can you give me some advice?很抱歉打扰您，我也遇到了这个问题，您能给我一些建议吗？
> 
> Download the original [MIMIC-CXR](https://physionet.org/content/mimic-cxr/2.0.0/) dataset.下载原始 MIMIC-CXR 数据集。

Thank you for your prompt reply. I am downloading the ' mimic-cxr-reports.zip ' file in the original mimic-cxr dataset. According to the description of the build _ mimic _ cxr _ jpg _ dataframe function, should I not change the code from if img _ extension = = ' jpg ' to if img _ extension = = '.dcm ' ?
